### ISSUE TITLE
Crash after use button back from scanner

### ISSUE THREAD

**Issue by Jean-BaptisteC** [jfoucry/Pilldroid#10]
**Android 12 - Pixel 6**

How reproduce:

- Open app -> open scanner
- back on main page with native button back on Android
- Crash appears not in the first time
```

5-12 18:11:06.733 22412 22412 E AndroidRuntime: FATAL EXCEPTION: main
05-12 18:11:06.733 22412 22412 E AndroidRuntime: Process: net.foucry.pilldroid, PID: 22412
05-12 18:11:06.733 22412 22412 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'android.os.Bundle android.content.Intent.getExtras()' on a null object reference
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at net.foucry.pilldroid.DrugListActivity.f0(Unknown Source:10)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at net.foucry.pilldroid.DrugListActivity.T(Unknown Source:0)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at z2.l.a(Unknown Source:4)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at androidx.activity.result.ActivityResultRegistry$1.g(Unknown Source:101)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at androidx.lifecycle.k$a.a(Unknown Source:14)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at androidx.lifecycle.k.g(Unknown Source:69)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at androidx.lifecycle.k.p(Unknown Source:72)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at androidx.lifecycle.k.l(Unknown Source:19)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at androidx.lifecycle.k.h(Unknown Source:9)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at androidx.lifecycle.s.a(Unknown Source:30)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at androidx.lifecycle.s$b.onActivityPostStarted(Unknown Source:2)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at android.app.Activity.dispatchActivityPostStarted(Activity.java:1377)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at android.app.Activity.performStart(Activity.java:8116)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at android.app.ActivityThread.handleStartActivity(ActivityThread.java:3732)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.performLifecycleSequence(TransactionExecutor.java:221)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.cycleToPath(TransactionExecutor.java:201)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.executeLifecycleState(TransactionExecutor.java:173)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:97)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2253)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:106)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7870)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
05-12 18:11:06.733 22412 22412 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

**Comment by jfoucry** [comment]
Same on my oneplus 5T lineageos 18.1

Thanks for pointing me.

Strange, but not important for now :-) Not sure to fix rapidly.
