### ISSUE TITLE
Exception when user rotate device

### ISSUE THREAD

**Issue by Jean-BaptisteC** [jfoucry/Pilldroid#49]
How to reproduce
- Start app (need consent dialog)
- Rotate device -> exception was generated

```
android.view.WindowLeaked: Activity net.foucry.pilldroid.WelcomeActivity has leaked window com.android.internal.policy.DecorView{1e24b2 V.E...... R....... 0,0-840,831 aid=1073741824}[WelcomeActivity] that was originally added here
at android.view.ViewRootImpl.<init>(ViewRootImpl.java:1099)
at android.view.ViewRootImpl.<init>(ViewRootImpl.java:1085)
at android.view.WindowManagerGlobal.addView(WindowManagerGlobal.java:396)
at android.view.WindowManagerImpl.addView(WindowManagerImpl.java:154)
at android.app.Dialog.show(Dialog.java:352)
at net.foucry.pilldroid.WelcomeActivity.askForComprehensive(WelcomeActivity.java:150)
at net.foucry.pilldroid.WelcomeActivity.onCreate(WelcomeActivity.java:82)
at android.app.Activity.performCreate(Activity.java:8767)
at android.app.Activity.performCreate(Activity.java:8745)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1519)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3928)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:4126)
at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:108)
at android.app.servertransaction.TransactionExecutor.executeNonLifecycleItem(TransactionExecutor.java:195)
at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:157)
at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:90)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:2544)
at android.os.Handler.dispatchMessage(Handler.java:107)
at android.os.Looper.loopOnce(Looper.java:232)
at android.os.Looper.loop(Looper.java:317)
at android.app.ActivityThread.main(ActivityThread.java:8501)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:552)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:878)
```

**Comment by jfoucry** [comment]
As I said inf another PR, Pilldroid has not be create with the ability to rotate the device. Did you think its essential?

**Comment by Jean-BaptisteC** [comment]
On mobile, it's not necessary but for tablet, it's very useful
